---
title: Deborah Saks
timezone: UTC
collections:
  postcards:
    title: Postcards
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: Deborah
    image: ''
    dimensions: ''
email: d_saks@yahoo.com
description: This is online portfolio of Deborah Saks, a Washington, D.C. based collage
  artist.
permalink: "/work/:title/"
baseurl: 
markdown: kramdown
